### ISSUE TITLE
VOCAB_QUDT-UNITS-ALL-v2.1.ttl missing

### ISSUE THREAD

**Issue by twhiteaker** [qudt/qudt-public-repo#1002]
I used to reference this file to get a list of all units:
https://raw.githubusercontent.com/qudt/qudt-public-repo/master/vocab/unit/VOCAB_QUDT-UNITS-ALL-v2.1.ttl

Today I'm getting 404.  Has it moved?  If it has been removed, what file should I reference instead?

**Comment by fkleedorfer** [comment]
We have set up a new build process. The file you want is no longer in the repository. 

You either have to [build it locally using maven](https://github.com/qudt/qudt-public-repo?tab=readme-ov-file#building) or you get it from the latest release zip, which would be

https://github.com/qudt/qudt-public-repo/archive/refs/tags/v2.1.44.zip
or 
https://github.com/qudt/qudt-public-repo/archive/refs/tags/v2.1.44.tar.gz

**Comment by steveraysteveray** [comment]
The other, more direct way, is to access it on the qudt.org website. We are just ironing out our publishing mechanism in light of our migration to Maven, but see [https://qudt.org/2.1/vocab/unit](https://qudt.org/2.1/vocab/unit). This will be updated with each new release.

**Comment by fkleedorfer** [comment]
Note, though, that the URI of the release zip that contains the file you want will change starting with the next release, too:

There currently is a snapshot release that you can use for testing:

https://github.com/qudt/qudt-public-repo/releases/download/snapshot/qudt-public-repo-2.1.45-SNAPSHOT.zip

This is because we build a release zip and add it to the github release as an asset.

**Comment by steveraysteveray** [comment]
Actually, depending on how you are using the graph in your work, you could also just use the unversioned URI, [https://qudt.org/vocab/unit](https://qudt.org/vocab/unit), which will always resolve to the latest version. Note that the base URI is also unversioned. Your choice.

I say this because we are upgrading our system to migrate to full semantic versioning soon.

**Comment by twhiteaker** [comment]
@steveraysteveray that's exactly what I was looking for.  Thanks!

**Comment by steveraysteveray** [comment]
Last comment!

Just in case you aren't aware, you can get a good overview of QUDT at our [home page](https://qudt.org/), and the [catalog page](https://www.qudt.org/2.1/catalog/qudt-catalog.html) is your entry point to all the vocabulary and schema graphs. Also, individual units etc. also resolve, such as http://qudt.org/vocab/unit/A for the Ampere. Content negotiation is used to deliver either an HTML page or a Turtle file, which you could use in your application if appropriate.
