### ISSUE TITLE
What to do about biological variants of counting (EU, CFU)

### ISSUE THREAD

**Issue by Toby-Broom** [qudt/qudt-public-repo#1041]
I wanted to add Endotoxins per "unit" (g/mL,...), its very much like CFU, the USP 85 requires that materials for human consumption are checked to ensure that the level are low, so we measure the concentration of endotoxins.  The endotoxins are a mixture of materials so you cannot say is mol/L or mol/g since this would imply a specific amount of a material.  One EU is about 1 pg of E. coli lipopolysaccharide but it could be that there is other biological material that are not E. coli so its not a 1:1 mapping.

The test measures the color change when you expose the sample to some antibodies and a chromogen.

I added this because CFU was there, I can see Steve's argument that its just another derivative of number/g, in which case we can create a domain specific ontology term for EU, in that case CFU would also be in the same domain of biological assays.

**Comment by Toby-Broom** [comment]
Also issue #276 would be similar.

**Comment by steveraysteveray** [comment]
@Toby-Broom, sorry I have been unresponsive. Big holiday week in the USA last week (Thanksgiving). Back now, however.

So, I'd like to hear your opinion on the relationship between your Endotoxin family of units, the Colony forming units, and the plaque forming units from way back (that I never took action on) in Issue #276. Do we need all three, and if so, do they have a skos:broader relationship? If not, is there a general version we can define?

**Comment by Toby-Broom** [comment]
Hi Steve, 

I liked your sugestion, in the end your just counting a material entity, we model these anyhow as there is many of these, we can assign NUM-PER-X as the units describing these, this keeps things neater vs blowing out QUDT with many varients of counting entities where every entity is a new quantitykind.  I think it comes back to how humans like to think about things in that they are count the thing so the units become thing/g or thing/mL.

If this is the way you want to go then you should remove some of the items that are just a count of entity, so CFU would be removed and maybe some other things?

As I wrote I only thought to create it since you have CFU already so I thought this was the decision that you had made but it opens a larger discussion.

**Comment by fkleedorfer** [comment]
I don't know about that. Isn't the beauty of Qudt: if I use the unit, it's in qudt? Qudt does not tell you, "don't be silly, that's not a unit, here is what serious people use for that." 

Think of the next person trying to find the unit you were trying to find. Will they end up happily using NUM-PER-x units?

**Comment by Toby-Broom** [comment]
I think thats my general question is what is the philiosphy?

Side question since EU is already taken in the TTL. what are the rule about naming the unit, since most align with the symbol but this is not possiable.

**Comment by fkleedorfer** [comment]
> what are the rule about naming the unit, since most align with the symbol but this is not possiable.

There is an article about that in our wiki:

https://github.com/qudt/qudt-public-repo/wiki/Unit-Vocabulary-Submission-Guidelines#qname-naming-rules

**Comment by steveraysteveray** [comment]
Speaking to the guiding philosophy, as mentioned by @Toby-Broom.

This issue of defining and finding units for different contexts is the tip of a very large iceberg that I will not go into on this thread. What is involved is the distinction between a qudt:Unit (context-free) and a qudt:Quantity (contextual). I continue to believe that the Colony forming units, the plaque forming units, and endotoxin counts are all contextual applications of a count per something (either per mass or per volume). As such, I believe we should not include them as QUDT units.

How is a user supposed to find them, you might ask? I would respond that the qudt:DimensionVector is your friend here. If you think about the dimensionality as being a count per, say, mass, you can interrogate the vocabulary to see what quantity kinds and units have that dimensionality. Here's what I got from our[ SPARQL end-point](https://www.qudt.org/fuseki/#/dataset/qudt/query), sorted alphabetically so that the quantity kinds are listed first.

```
1 | <http://qudt.org/vocab/quantitykind/CostPerMass>
3 | <http://qudt.org/vocab/quantitykind/InverseMass>
2 | <http://qudt.org/vocab/unit/CHF-PER-KiloGM>
11 | <http://qudt.org/vocab/unit/NUM-PER-GM>
12 | <http://qudt.org/vocab/unit/NUM-PER-HectoGM>
13 | <http://qudt.org/vocab/unit/NUM-PER-MilliGM>
4 | <http://qudt.org/vocab/unit/PER-GM>
5 | <http://qudt.org/vocab/unit/PER-KiloGM>
6 | <http://qudt.org/vocab/unit/PER-LB>
7 | <http://qudt.org/vocab/unit/PER-MilliGM>
8 | <http://qudt.org/vocab/unit/PER-OZ>
9 | <http://qudt.org/vocab/unit/PER-TON>
10 | <http://qudt.org/vocab/unit/PER-TONNE>
```
(Arguably, we could add quantitykind:CountPerMass to our vocabulary if that helps).

Armed with this information, the user can then choose the unit that best fits their application, and associate it with a qudt:Quantity of their design, called something like biologydomain:EndotoxinCount or whatever they like.

I take this position because other ontologists have gotten themselves tied up into knots trying to create contextual units and what they end up calling "pseudo units" such as CO2EquivalentMass with no end in sight, as I had mentioned [earlier](https://github.com/qudt/qudt-public-repo/pull/1006#issuecomment-2477330990).

Option 1:
As pointed out by @Toby-Broom, we should therefore deprecate unit:CFU as well.

Option 2:
If we believe this approach is not user-friendly enough, I'm open to suggestions for more intuitive ways for users to find "units" that they are comfortable using, without risking bloating the units vocabulary with many, many variants of the same concept.

**Comment by fkleedorfer** [comment]
Ok, thanks for sharing your reasoning. I would go with your option 1 then, and maybe @ralphtq can come up with a good solution for this problem on the UI side.

**Comment by steveraysteveray** [comment]
The OM ontology is what I had in mind when talking about ontologists tying themselves in knots. I support the idea of contextual qudt:Quantity instances analogous to VolumetricViableCount. (Note that OM's concept of "quantity" is our concept of qudt:QuantityKind.). QUDT.org does not curate collections of qudt:Quantity instances, although we are considering housing community-maintained collections of Quantity, since they are domain-specific. This goes along with our interest in supporting community-maintained profiles of Units and QuantityKinds.

A version of my Option 2 above could be community-supported extensions to the Units vocabulary instead of forcing the use of qudt:Quantity, if there was interest in that.

Final note: given your comment above, @Toby-Broom, I'm confused about your PR #1040 where you are adding more CFU-related units. I'm not sure what to do with it - are we going to deprecate CFU or expand it?

**Comment by ralphtq** [comment]
> The OM ontology is what I had in mind when talking about ontologists tying themselves in knots. I support the idea of contextual qudt:Quantity instances analogous to VolumetricViableCount. (Note that OM's concept of "quantity" is our concept of qudt:QuantityKind.). QUDT.org does not curate collections of qudt:Quantity instances, although we are considering housing community-maintained collections of Quantity, since they are domain-specific. This goes along with our interest in supporting community-maintained profiles of Units and QuantityKinds.

Strong agreement

> 
> A version of my Option 2 above could be community-supported extensions to the Units vocabulary instead of forcing the use of qudt:Quantity, if there was interest in that.

Strong agreement

**Comment by Toby-Broom** [comment]
@steveraysteveray I did that before we had this discussion, so if we are in agreement I can take them out.

We didn't do for QUDT but we extend where needed extra things so we can work then make the request to the upper levels as needed.

In this specific case, maybe USP would like to extend since they are the authoritative source of these domain specific units.

**Comment by steveraysteveray** [comment]
I think that is best. You could still add the mass ratio units that were in there, unit:NanoGM-PER-MilliGM.

Meanwhile, I will submit a PR deprecating the Colony forming unit family, with a redirection to the underlying context-free unit.

**Comment by buerokrata** [comment]
Hi All, I found this discussion very intersting, and I would be keen to challenge some of @steveraysteveray 's points on items like:
- contextual vs non-contextual quantities (and how any well measured quantity has a 'right' to become a unit)
- how counting cells, persons, frames, rotations and other things are more akin to counting 'metres' than just pure contextual nuances, unless 'metre' is also just contextual
- that the reason to ignore a vast array of 'contextual' units just because they would lead to many new units is a fairly weak one; couldn't we aim for a more axiomatic approach of building up a unit system?

Is there a forum or a more generic issue for such a discussion?

**Comment by fkleedorfer** [comment]
Hi @buerokrata, always good to discuss! The [Discussions](https://github.com/qudt/qudt-public-repo/discussions) section of the repo should be a good place for this. Feel free to start a new topic!

**Comment by Toby-Broom** [comment]
@buerokrata I made a discussion, also agree its good to explore! here #1079
