### ISSUE TITLE
Unit for gross tonnage

### ISSUE THREAD

**Issue by veleda** [qudt/qudt-public-repo#158]
I can't seem to find a unit for [gross tonnage](https://en.wikipedia.org/wiki/Gross_tonnage) (gt) in [http://qudt.org/vocab/unit/#](http://qudt.org/vocab/unit/#).  May this unit be included? :ship:

**Comment by jhodgesatmb** [comment]
Yes, but you will want to submit it according to the unit submission guidelines:

https://github.com/qudt/qudt-public-repo/wiki/Unit-Vocabulary-Submission-Guidelines

This way you can get your unit added the most quickly.

Jack Hodges

**Comment by steveraysteveray** [comment]
There is a bigger question here, which is whether Gross tonnage is really a qudt:QuantityKind or a qudt:Unit.
If I'm reading the Wikipedia article correctly:
"Gross tonnage (GT, G.T. or gt) is a nonlinear measure of a ship's overall internal volume."

...leading me to conclude it's a specialized, nonlinear measure of volume, correct? We can handle that, using a skos:broader relation between it and quantitykind:Volume.

But the text then goes on to say that the method for calculating GT uses cubic meters. Correct?

How is this term used in practice? Does one say:
1. The GT value of my ship is 3458.2 ?
or does one say:
2. The volume of my ship is 3458.2 GT ?

I ask to better understand whether this is being treated like a unit or a quantity kind.

As a unit, it will be challenging, since it is nonlinear and dependent on the ship. Our current qudt:conversionMultiplier property assumes the value is constant, but we do recognize that in the future we will need to support nonlinear conversions.

**Comment by steveraysteveray** [comment]
Reading further [here](https://en.wikipedia.org/wiki/Tonnage), 
I see:
"Gross tonnage is therefore a kind of capacity-derived index that is used to rank a ship for purposes of determining manning, safety, and other statutory requirements and is expressed simply as GT, which is a unitless entity, even though it derives from the volumetric capacity in cubic metres."

So, I suppose we should treat this like a unitless scale, which has no conversion multiplier. It would reference quantitykind:Dimensionless.

Does this sound right?

**Comment by jhodgesatmb** [comment]
Ok, I was going down the procedural path, but all of our references for TON are in the units vocabulary and some of them are Mass, some are a Force, and some are Volume.

Jack

**Comment by Kristian-source** [comment]
You would say that the GT value of my ship is 3458,2. It is a value that indicates the size of a ship. The combined volum of certain spaces on a ship is used to calculate this value. The GT value is used by autorities to set requirements to the ship.

**Comment by qudt** [comment]
@Kristian-source and @veleda,  We are still debating the correct modeling of GT. Please stay tuned!

**Comment by steveraysteveray** [comment]
unit:GT is being added in PR #162. Hope it meets your needs!

**Comment by veleda** [comment]
Splendid! Thank you!
