### ISSUE TITLE
VOCAB_QUDT-QUANTITY-KINDS-NIST-CONSTANTS-v2.0.ttl Contains Missing Imports

### ISSUE THREAD

**Issue by dm-work** [qudt/qudt-public-repo#188]
The file, `VOCAB_QUDT-QUANTITY-KINDS-NIST-CONSTANTS-v2.0.ttl`, contains imports of resources that are not included in the [QUDT Release 2.1.4](https://github.com/qudt/qudt-public-repo/releases/tag/v2.1.4):

```
<http://qudt.org/2.0/vocab/nist-constants>
  owl:imports <http://qudt.org/2.0/vocab/sou/si> ;
  owl:imports <http://qudt.org/2.0/vocab/unit/base> ;
  owl:imports <http://qudt.org/2.0/vocab/unit/planck> ;
```

**Comment by steveraysteveray** [comment]
Daniel,
Thanks for all your work on helping to make QUDT consistent. Let me explain what my approach has been.

Last December, I consolidated the quantity kinds into one graph. They had been distributed among various disciplines before that, which was confusing and a maintenance headache. I did, however, leave the folder quantitykinds/standards-based-quantitykinds intact for the time being, so that we could examine the contents more carefully and harvest any valuable content before deleting them. Eventually all those graphs in that folder will be removed.

The same approach is being used with the "types" folder and the "scales" folder. All on the to-do list.

Do let me know where else you are checking, and I can tell you what the plans are.

- Steve
