### ISSUE TITLE
widening the scope of qudt:isoNormativeReference 

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [qudt/qudt-public-repo#226]
Dear QUDT-Team

Many units exists, which may be not ISO standard but on a different level, e.g. EN. Hence, I was wondering if it would make sense to widen the scope of property

> http://qudt.org/schema/qudt/isoNormativeReference .

For example the property could be deprecated and an substitute could be introduced

> http://qudt.org/schema/qudt/normativeReference .

Best

Georg

**Comment by jhodgesatmb** [comment]
I do not understand what you are suggesting and neither of those links were found.

The intention was always to support all of the systems of units/quantities standards.

Jack

**Comment by steveraysteveray** [comment]
Interesting suggestion. We will discuss. One option might be to retain the isoNormativeReference, given its dominance in international standards, but also have a "non-iso" normative Reference property. We do have informativeReference, but I think you are asking for more than just that.

**Comment by ralphtq** [comment]
Hi Georg,

The response from Jack was perhaps confusing. I will clarify things in this reply.

Both properties are defined, the ISO property is a sub property of normative reference.

qudt:normativeReference
  rdf:type owl:AnnotationProperty ;
  dct:description "Provides a way to reference information that is an authorative source providing a standard definition"^^rdf:HTML ;
  rdfs:isDefinedBy <http://qudt.org/2.1/schema/qudt> ;
  rdfs:label "normative reference" ;
.

qudt:isoNormativeReference
  rdf:type owl:AnnotationProperty ;
  dct:description "Provides a way to reference the ISO unit definition."^^rdf:HTML ;
  rdfs:isDefinedBy <http://qudt.org/2.1/schema/qudt> ;
  rdfs:label "normative reference (ISO)" ;
  rdfs:subPropertyOf qudt:normativeReference ;
.

‘qudt:normativeReference’ is defined on an “Aspect Class” called ‘qudt:Verifiable’ with is inherited by: qudt:Comment, qudt:Prefix, qudt:QuantityKind, qudt:Rule and qudt:Unit.

Having said this the links to these properties do not currently resolve to an HTML page.


Regards,

Ralph Hodgson

**Comment by steveraysteveray** [comment]
Just to add to what Ralph just said, eventually we hope to provide resolvable URIs for all our classes and properties, but that is not yet in place.

**Comment by ralphtq** [comment]
*   this the links to these properties do not currently resolve to an HTML page

That is what I meant. I did not go to the repository (I don’t keep it open all the time) to check because links were provided. I want to be clear about the request. Are you suggesting that the ISO reference be removed or that others be added? I think that you are suggesting the former but I just want to be clear.

Jack

From: "rhodgson@topquadrant.com" <rhodgson@topquadrant.com>
Date: Monday, September 7, 2020 at 10:11 AM
To: qudt/qudt-public-repo <reply@reply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>, Steve Ray <steve.ray@qudt.org>, "jhodges@qudt.org" <jhodges@qudt.org>
Subject: Re: [qudt/qudt-public-repo] widening the scope of qudt:isoNormativeReference (#226)

Hi Georg,

The response from Jack was perhaps confusing. I will clarify things in this reply.

Both properties are defined, the ISO property is a sub property of normative reference.

qudt:normativeReference
  rdf:type owl:AnnotationProperty ;
  dct:description "Provides a way to reference information that is an authorative source providing a standard definition"^^rdf:HTML ;
  rdfs:isDefinedBy <http://qudt.org/2.1/schema/qudt<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fqudt.org%2F2.1%2Fschema%2Fqudt&data=02%7C01%7Cjack.hodges%40siemens.com%7Cfca6ace2f4e7457ebec608d853511590%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C637350955003869420&sdata=QC4UVsHLPvqnhn%2BumcH78oV1TnelQnvSlOT7XApPkI8%3D&reserved=0>> ;
  rdfs:label "normative reference" ;
.

qudt:isoNormativeReference
  rdf:type owl:AnnotationProperty ;
  dct:description "Provides a way to reference the ISO unit definition."^^rdf:HTML ;
  rdfs:isDefinedBy <http://qudt.org/2.1/schema/qudt<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fqudt.org%2F2.1%2Fschema%2Fqudt&data=02%7C01%7Cjack.hodges%40siemens.com%7Cfca6ace2f4e7457ebec608d853511590%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C637350955003874394&sdata=JIm57RiMipnIypB5sOEyJKQOTyNy1KzfrNPD84iFA8o%3D&reserved=0>> ;
  rdfs:label "normative reference (ISO)" ;
  rdfs:subPropertyOf qudt:normativeReference ;
.

‘qudt:normativeReference’ is defined on an “Aspect Class” called ‘qudt:Verifiable’ with is inherited by: qudt:Comment, qudt:Prefix, qudt:QuantityKind, qudt:Rule and qudt:Unit.

Having said this the links to these properties do not currently resolve to an HTML page.


Regards,

Ralph Hodgson



On Sep 7, 2020, at 10:52 AM, jhodgesatmb <notifications@github.com<mailto:notifications@github.com>> wrote:


I do not understand what you are suggesting and neither of those links were found.

The intention was always to support all of the systems of units/quantities standards.

Jack

**Comment by GeorgFerdinandSchneider** [comment]
Hi @steveraysteveray  @ralphtq !

thanks for the clarification that the property.

> qudt:normativeReference

already exist - I was not aware of. I was looking for this so I suppose we can close this issue. 

Thanks and BR

Georg
