### ISSUE TITLE
Sub-properties of qudt:unit

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#273]
`qudt:applicableUnit` and qudt:relevantUnit` have range `qudt:Unit` and no domain.

These should either be
- sub-properties of `qudt:unit`
- deprecated, and guarded constraints (Restrictions) applied on the relevant classes instead.

**Comment by steveraysteveray** [comment]
I'm still polishing the qudt:appropriateUnit property, which lives as a magic property in the OWL world, and as a SHACL shape in the SHACL world. It's almost working perfectly, but not quite. Once that is done, I'm hoping we can deprecate these two properties.

Note that once this is done, we will need to review the hasQuantityKind property values from Unit instances to QuantityKinds, because they determine the qudt:appropriateUnit values (illustrated [here](https://github.com/qudt/qudt-public-repo/issues/272#issuecomment-720146569)).

**Comment by steveraysteveray** [comment]
The qudt:appropriateUnit property is now fully implemented, in PR #277. 
I would like to deprecate qudt:applicableUnit and qudt:relevantUnit, since they will just cause confusion with qudt:appropriateUnit. 

This is being addressed in Issue #281.

**Comment by steveraysteveray** [comment]
Simon, will this address your original issue here? If so we can close this one.
