### ISSUE TITLE
Duplicated units

### ISSUE THREAD

**Issue by jmkeil** [qudt/qudt-public-repo#302]
Using a [comparison of unit ontologies with ABECTO](https://github.com/fusion-jena/abecto-unit-ontology-comparison) I became aware of the following unmarked duplicates:
* [ ] ~~http://qudt.org/vocab/unit/BTU_IT-IN-PER-FT2-HR-DEG_F = http://qudt.org/vocab/unit/BTU_IT-IN-PER-HR-FT2-DEG_F~~ (see #237)
* [ ] ~~http://qudt.org/vocab/unit/BTU_IT-IN-PER-FT2-SEC-DEG_F = http://qudt.org/vocab/unit/BTU_IT-IN-PER-SEC-FT2-DEG_F~~ (see #237)
* [ ] http://qudt.org/vocab/unit/Hundredweight_US = http://qudt.org/vocab/unit/CWT_SHORT
* [ ] http://qudt.org/vocab/unit/GAUSS = http://qudt.org/vocab/unit/Gs (and http://qudt.org/vocab/unit/T_Ab)
* [ ] http://qudt.org/vocab/unit/TON_SHORT = http://qudt.org/vocab/unit//TON_US

This further pointed me to the following duplicates:
* [ ] http://qudt.org/vocab/unit/Hundredweight_UK = http://qudt.org/vocab/unit/CWT_LONG
* [ ] http://qudt.org/vocab/unit/TON_US-PER-HR = http://qudt.org/vocab/unit/TON_SHORT-PER-HR
* [ ] http://qudt.org/vocab/unit/TON_US-PER-YD3 = http://qudt.org/vocab/unit/TON_SHORT-PER-YD3
* [ ] http://qudt.org/vocab/unit/TON_LONG = http://qudt.org/vocab/unit/TON_UK
* [ ] http://qudt.org/vocab/unit/TON_LONG-PER-YD3 = http://qudt.org/vocab/unit/TON_UK-PER-YD3

**Comment by steveraysteveray** [comment]
This issue of duplicates is not as absolute as we originally thought. Specifically, in our qname naming conventions (documented [here](https://github.com/qudt/qudt-public-repo/wiki/Unit-Vocabulary-Submission-Guidelines#qname-naming-rules)), we had originally simply said that hyphenated terms should appear in alphabetical order. Unfortunately, this leads to some counterintuitive qnames, such as M-N instead of N-M for Newton-Metre. So now, as documented in rule 5b, we allow for the more common ordering to be used.

The question then becomes one of whether we should allow BOTH the strict alphabetical ordering AND the common version. At this point, we are allowing both, meaning there will be duplicate qnames for the same concept. In such cases, we will be indicating such duplicates with a relation. We are currently discussing whether to use owl:sameAs or qudt:exactMatch for this.

**Comment by dr-shorthair** [comment]
`skos:exactMatch` is intended for mappings between concepts in different concept-schemes. So would not be used within a vocabulary or catalogue. I guess you would want similar semantics? 

`owl:sameAs` implies that the local graphs can be merged. That is fine here. It is only problematics if it leads to constraint violations like multiple different `skos:prefLabel` values - but I don't think we use that.

**Comment by steveraysteveray** [comment]
We discussed this issue today, and we believe that since skos:prefLabel is an AnnotationProperty, it should not be a problem with OWL reasoners. Accordingly, we plan to move forward with using owl:sameAs to relate synonymous units (and synonymous quantitykinds), rather than qudt:exactMatch. Stay tuned for a PR.

**Comment by dr-shorthair** [comment]
Indeed, it would not be a problem with OWL reasoners. Iff `skos:prefLabel` was involved, then a SKOS checker might flag an error, but I don't believe QUDT uses `skos:prefLabel` anyway, so it is probably a red herring.
