### ISSUE TITLE
SPARQL endpoint for units graph?

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#355]
I'm trying to explain to the UCUM folks how it is possible to query the QUDT dataset using a UCUM code. 
I could do this easily if there was an accessible SPARQL Query endpoint.

**Comment by steveraysteveray** [comment]
We're working out the kinks on a SPARQL endpoint accessible programmatically, but we DO have a SPARQL query interface on our [EDG server](http://www.qudt.org/edg/tbl/swp?_viewName=home). If you don't know how to bring up the SPARQL query layout, I encourage you to view the [instructional video](http://qudt.org/video/intro.html) available at that site. The 2:35 minute mark deals with the SPARQL query. Things have improved since the video. Queries now support variables, so you can just select the "UCUM search" query from the library and press the "play" button.
Here's a screenshot when I searched for PC as the UCUM code:
![image](https://user-images.githubusercontent.com/1130189/108108621-b5cb8380-7045-11eb-8e35-35ed13e08aff.png)

**Comment by steveraysteveray** [comment]
Just cleaning up here. The SPARQL endpoint is fully functional at:

http://www.qudt.org/fuseki
