### ISSUE TITLE
PSU not in the units catalogue

### ISSUE THREAD

**Issue by dr-shorthair** [qudt/qudt-public-repo#384]
http://qudt.org/vocab/unit/PSU does not appear in http://www.qudt.org/doc/DOC_VOCAB-UNITS.html 
Is that because it is 'not recommended' ?

**Comment by steveraysteveray** [comment]
Just guessing, but I notice it doesn't have a rdfs:isDefinedBy, and something in the back of my head says maybe that is used by the script to generate the html page....

A quick query reveals the following culprits:
![image](https://user-images.githubusercontent.com/1130189/114798316-f136b580-9d49-11eb-9dff-9cf65da48a96.png)

Probably should start writing some validation tests for this kind of thing...

If you'd like to submit a PR with these fixes, that'd be great. Otherwise, I'll put it on the queue.

**Comment by dr-shorthair** [comment]
See PR #385
