### ISSUE TITLE
Representing "per pixel" or "per channel" units

### ISSUE THREAD

**Issue by jat255** [qudt/qudt-public-repo#463]
Something come across quite commonly in spectrometry and electron/scanning probe microscopy is the concept of detector dispersion. This typically comes in the form of an "amount per channel" (or per pixel) such as eV/channel. I'm just beginning with QUDT, so perhaps there's already a way to represent this. If so, please ignore. 

Seems related to #435.

**Comment by steveraysteveray** [comment]
There is a fuzzy boundary between what constitutes a Unit of measure, and what is simply a Quantity. For example, the number of people per household is not (in my view) a Unit of measure, but rather a contextual Quantity that is measured as a count (a suitable unit is unit:NUM) where the denominator (household) is the context in which you are measuring that count. The Quantity here is dimensionless, since "count" is dimensionless as is "household", which does not map to any of the 7 base dimensions.

The reason I say it is fuzzy is because some contextual measures become more widespread in use and at some point they might start to be used as a Unit. I'll wax a bit philosophical for a moment by pointing out that all Units are really just Quantities with well-defined contexts, such as the definition of any of the SI base units. (e.g. The second is defined as being equal to the time duration of 9,192,631,770 periods of the radiation corresponding to the transition between the two hyperfine levels of the fundamental unperturbed ground-state of the caesium-133 atom. ([Wikipedia](https://en.wikipedia.org/wiki/Second)))

So, I'm wondering if unit:NUM or unit:EV might be enough for you, where your implementation provides the context "per channel"?

**Comment by jat255** [comment]
Yes, I agree with you about the fuzziness of it. Indeed "channels" or "pixels" are not really units; they just happen to be used as such since it's convenient. Indeed (to me at least), the concept of "eV" and "eV per something" (whether that *something* is a physical unit or a quantity) For my application, I was hoping to store just the value and unit of a quantity without any additional context.  Something like dispersion could be:

```python
{
 "dispersion": {
    "value": 0.3,
    "unit": "unit:EV-PER-CHANNEL"
  }
}
``` 

Since that compound unit does not exist, I suppose the following is possible:

```python
{
 "dispersion_per_channel": {
    "value": 0.3,
    "unit": "unit:EV"
  }
}
``` 

but that encodes some information about the dimensionality (for lack of a better term) in the arbitrary parameter name, which is not very satisfying.

I suppose all this has me wondering that if "quantity-per-unit" is available (such as http://qudt.org/vocab/unit/NUM-PER-M3), shouldn't the inverse of "unit-per-quantity" also be?  This would allow something like:

```python
{
 "dispersion": {
    "value": 0.3,
    "unit": "unit:EV-PER-NUM"
  }
}
``` 

which, while less specific about "channel", at least indicates that the energy is being recorded as discrete amounts per some quantity, rather than just a "raw" energy. 

I realize this would basically double the size of the vocabulary if this were to be implemented for every physical unit, so perhaps that's not desirable either. I'm not really sure what the right approach is, so happy to defer to the experts here!

**Comment by steveraysteveray** [comment]
I like your suggestion of

```
{
 "dispersion_per_channel": {
    "value": 0.3,
    "unit": "unit:EV"
  }
}
```
Regarding your misgivings about the "encoding of dimensionality", is that really a problem? The dimensionality is, in this case, energy per a dimensionless thing (channel). If all your "things" are real-world objects, like channels, households, etc., they are all dimensionless. If any of your "things" actually have physical dimensionality, then that can be captured in the dimension vector.

**Comment by jat255** [comment]
Sorry for the delay getting back to this. I've decided to encode "per channel" into the value name like suggested, so I will close this
