### ISSUE TITLE
quantitykind:VolumePerArea referenced but not defined

### ISSUE THREAD

**Issue by fkleedorfer** [qudt/qudt-public-repo#593]
```
unit:M3-PER-HA qudt:hasQuantityKind quantitykind:VolumePerArea 
```
but there are no triples with `quantitykind:VolumePerArea` in the subject position.

`quantitykind:VolumePerArea` is new in v2.1.20, which probably means that we should add its definition. I'll start work on a PR with what I can come up with myself, but I'll probably need a bit of help to fill in all the properties.

**Comment by fkleedorfer** [comment]
Digging. `quantitykind:VolumePerArea` was introduced in #571

**Comment by fkleedorfer** [comment]
I am not sure about the quantitykind. `unit:M3-PER-HA`, which introduces `quantitykind:VolumePerArea`, has this vector:
```
unit:M3-PER-HA  qudt:hasDimensionVector qkdv:A0E0L1I0M0H0T0D0 .
```
... which looks wrong to me. We are using the same dimension in nominator and denominator, but with different exponents. Here, the idea seems to be that they can be reduced as `L^3/L^2 = L^1`. I believe this is the only unit that has unequal positive and negative exponents for the same dimension. In other cases, where both exponents are the same, such as `unit:M3-PER-M3`, we instead say that it's just a ratio (`qkdv:A0E0L0I0M0H0T0D1`). 

This is an interesting case, and I see three options:
* use `qkdv:A0E0L1I0M0H0T0D0` and say, `unit:M3-PER-HA` can be converted into any length.
* use `qkdv:A0E0L0I0M0H0T0D1` and say it is a ratio, theoretically convertible into any other ratio, but that hasn't bothered anyone so far
* try something new and use `qkdv:A0E0L3-2I0M0H0T0D0`, making it a very narrow category of ratios, but we could convert between, say `unit:M3-PER-HA` and a (hypothetical) `unit:MilliM3-PER-MilliM2`. Or use `qkdv:A0E0L3-2I0M0H0T0D1` to still mark it as a ratio.

Food for thought, but in the PR, I'll go with the vector used by `unit:M3-PER-HA`

**Comment by steveraysteveray** [comment]
I believe your first option is best, but also including the numerator and denominator dimensions.

On your option 2, I don't like it because the fact that it is a ratio doesn't mean it is dimensionless, so D1 would be incorrect. You are correct in observing that with few exceptions, all of our current uses of the numerator and denominator dimensions have been for dimensionless ratios, where the numerator and denominator values are equal (as described in our [wiki](https://github.com/qudt/qudt-public-repo/wiki/User-Guide-for-QUDT#6-using-quantity-kinds-with-dimensionless-quantities)). But there's no principled reason we should not also use it for cases such as the current VolumePerArea. Applications could choose to simply compare the qudt:hasDimensionVector values, or they could go one step further and check the numerators and denominators (if they exist), to ensure commensurability.

Your option 3 scares me. I think the the use of numerator and denominator provides this functionality.

I invite others to weigh in.
