### ISSUE TITLE
MOL-PER-TONNE

### ISSUE THREAD

**Issue by meganrwong** [qudt/qudt-public-repo#671]
Hi Steve 
I'm new to the request process. I have read your instructions however I'm in need of some guidance. 
First of all, unless I missed if I can't see Mol per Tonne so would like to make that request 

I've done this, let me know if I'm off track for submission process: 
![image](https://user-images.githubusercontent.com/49380601/230267720-03c81699-2e9c-483d-8530-0e5e849396f8.png)

My question is how do I best submit these changes now/to which file do I make the changes to push?

Do I work in mw-mynewbranch on file new_correct_info.ttl (or a different file in qudt-public-repo?) then commit change and push to qudt-public-repo? (I'm using GitHub Desktop btw)

Your guidance is much appreciated since I have a couple more to submit also

**Comment by steveraysteveray** [comment]
Hi @meganrwong. Thanks for contributing!
I took another look at our [guidance](https://github.com/qudt/qudt-public-repo/wiki/Unit-Vocabulary-Submission-Guidelines), and I realize it is a bit ambiguous when we say "code should be added either directly to the file (preferred), or...". I'm presuming you have forked or cloned our repository. What the guidance means is, while in your own branch, go ahead and edit the VOCAB_QUDT-UNITS-ALL-v2.1.ttl file, then do the usual "git add...", "git commit..." etc., as per our [GoodGitPractices](https://github.com/qudt/qudt-public-repo/wiki/GoodGitPractices) guide also on the wiki.

Regarding your example above, you are missing the qudt:hasDimensionVector triple (see our [required unit properties](https://github.com/qudt/qudt-public-repo/wiki/Unit-Vocabulary-Submission-Guidelines#required-unit-properties)). The easiest way to figure out the dimension vector, since you are already pointing to some relevant QuantityKinds, is to look at them and copy over the dimension vector they point to. 

Secondly, the conversion multiplier should be 0.001, not 1000. Keep in mind that the conversion multiplier is "the multiplier to convert quantities using this unit to quantities using the SI unit for this quantity kind." This is because the Tonne is in the denominator. Thinking about it, 1 MOL/TONNE is going to map to a much smaller number of MOL/KiloGM.

Finally, after you git push, just submit a Pull Request and we will review.

Feel free to ask if I'm not being clear!

**Comment by meganrwong** [comment]
Fixed the conversion multiplier 
Based dimension dimension vector and quanity kinds off https://qudt.org/vocab/unit/CentiMOL-PER-KiloGM
all the quantity kinds have the same dimension vector
Any feedback particularly on quantity kinds @dr-shorthair  ?

unit:MOL-PER-TONNE
  a qudt:Unit ;
  qudt:conversionMultiplier .001 ;
  qudt:hasDimensionVector dimensionvector A1E0L0I0M-1H0T0D0 ;
  dcterms:description "Mole Per Tonne (\(mol/t\)) is a unit of Molality" ;
  qudt:hasQuantityKind quantitykind:AmountOfSubstancePerUnitMass ;
  qudt:hasQuantityKind quantitykind:IonicStrength ;
  qudt:hasQuantityKind quantitykind:MolalityOfSolute ;
  qudt:symbol "mol/t" ;
  qudt:ucumCode "mol.t-1" ;
  qudt:ucumCode"mol/t" ;
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
  rdfs:label "Mol per Tonne"@en ; 
.

**Comment by dr-shorthair** [comment]
qudt:hasQuantityKind quantitykind:AmountOfSubstancePerUnitMass ;
~qudt:hasQuantityKind quantitykind:IonicStrength ;~
~qudt:hasQuantityKind quantitykind:MolalityOfSolute ;~
