### ISSUE TITLE
Incorrect description and dimension for unit:C2-M-PER-J

### ISSUE THREAD

**Issue by jsimonclark** [qudt/qudt-public-repo#691]
For the term unit:C2-M-PER-J, the description and expression refer to it as C2.m2/J instead of C2.m/J Also the dimension vector is dimension:A0E2L0I0M-1H0T4D0, but it should be dimension:A0E2L-1I0M-1H0T4D0.

**Comment by steveraysteveray** [comment]
Thanks! Fixed in PR #692.

**Comment by steveraysteveray** [comment]
Upon closer inspection, unit:C2-M-PER-J doesn't seem to correspond to any useful unit in the real world. The problem you found is actually due to the fact that the atomic unit of Polarizability is actually unit:C2-M2-PER-J, which has the original dimension vector. I have renamed unit:C2-M-PER-J to unit:C2-M2-PER-J (in the upcoming PR).
