### ISSUE TITLE
Page not found (HTTP 404) on import

### ISSUE THREAD

**Issue by LucasVerhelst** [qudt/qudt-public-repo#715]
When following all the imports in the QUDT files I found that the import of [http://qudt.org/2.1/schema/shacl/overlay/qudt](http://qudt.org/2.1/schema/shacl/overlay/qudt) produces a HTTP 404 error.

The file that the import is stated in is: [‎schema/shacl/SCHEMA_QUDT_NoOWL-v2.1.ttl](https://github.com/qudt/qudt-public-repo/blob/37811db26d398469999c5d9b4ceec5baf8fb9a4a/schema/shacl/SCHEMA_QUDT_NoOWL-v2.1.ttl#L76)

Which file is meant to be imported? How should this be resolved?

**Comment by steveraysteveray** [comment]
I gather you are loading the graphs from the web rather than a downloaded copy of the Release. You correctly point out that we have not made a resolvable version of http://qudt.org/2.1/schema/shacl/overlay/qudt on the web - I should correct that. In the meantime, it can be found as part of the Release, as well as on this repo. The filename is [SHACL-SCHEMA-SUPPLEMENT_QUDT-v2.1.ttl](https://github.com/qudt/qudt-public-repo/blob/main/schema/shacl/SHACL-SCHEMA-SUPPLEMENT_QUDT-v2.1.ttl)

**Comment by steveraysteveray** [comment]
This should be working for you now, including the web access, so I'm closing this.
