### ISSUE TITLE
pH is defined incorrectly

### ISSUE THREAD

**Issue by TobyAutoChem** [qudt/qudt-public-repo#891]
There is an inconsistent definition of pH

http://qudt.org/vocab/unit/PH

In the body you define that the units of the quantity pH are mol/L but you define pH as a unit.

Additionally definitions from IUPAC https://doi.org/10.1039/9781847557889 Section 2.13. would use an alternate definition of the quantity.

**Comment by steveraysteveray** [comment]
The current description for unit:PH is "the negative decadic logarithmus of the concentration of free protons (or hydronium ions) expressed in 1 mol/l." Other than the extra "1" that should not be there, the intention of the description is that the concentration of the free protons should be expressed in moles per litre, and then take the negative logarithm (base 10) of that number to give you the pH value. That still seems to be a valid description to us.

Meanwhile, we also have a quantitykind:PH, primarily because common usage is for a person to ask "What is the pH of this liquid?" That usage is much like someone saying "What is the temperature of this liquid," where temperature and pH are quantity kinds. In the case of pH, the only valid unit to use for that quantity kind is unit:PH.

**Comment by TobyAutoChem** [comment]
I check out the 1st topic in some more details and ask another question if I have one.

Here is the IUPAC definition, the imprecise one is true for a low concentration where aH+ ≂ [H+], e.g. 1 mol/L HCl has pH of 0, however you can get 12 mol/L HCl then it does not work anymore but the material still has a pH.

![Screenshot 2024-04-17 170031](https://github.com/qudt/qudt-public-repo/assets/95632281/ef1c13d3-69fc-4ec8-8701-261156d08993)

My general observation is people confuse terms unit and the symbol

**Comment by steveraysteveray** [comment]
The validation test mentioned above has been added in PR #901.

**Comment by steveraysteveray** [comment]
This has been handled by #906 and #907.
