### ISSUE TITLE
rdfs:label inconsistent with style guide

### ISSUE THREAD

**Issue by berrisfordjohn** [qudt/qudt-public-repo#910]
in the style guide "per" should not be capitalised.
from [https://github.com/qudt/qudt-public-repo/wiki/Unit-Vocabulary-Submission-Guidelines](https://github.com/qudt/qudt-public-repo/wiki/Unit-Vocabulary-Submission-Guidelines) 
"Case - In QUDT, Titlecase means that "per" will not be capitalized

Microgray
Picocoulomb
Becquerel Second per Cubic Metre
Erg per Gram Second
Gray per Second
Microradian
Minute
"

However, Units there are 561 examples where "per" is capitalised in rdfs:label - the inconsistent labels are included in the attached file.
[qudt_per_caps.csv](https://github.com/qudt/qudt-public-repo/files/15163712/qudt_per_caps.csv)

How would you like this addressed? Would you like a pull request with these corrected?

**Comment by berrisfordjohn** [comment]
pull request https://github.com/qudt/qudt-public-repo/pull/915

**Comment by jhodgesatmb** [comment]
We have not developed a strong requirement for labels as we have for qnames, since there is variability in labels that cannot exist in qnames (and labels are annotations). Others may see it differently.Jack Hodges, Ph.D.Arbor StudiosOn Apr 30, 2024, at 7:59 AM, John Berrisford ***@***.***> wrote:﻿
pull request #915
